.TH GS_TO_CSV 1 2020-12-11 LMSSTAR

.SH NAME
gs_to_csv.sh

.SH SYNOPSIS
.B gs_to_csv
#USAGE: ./gs_to_cvs.sh (input filename) (output filename) (exam name)
#Example: ./gs_to_cvs.sh example/example1.csv example/output.csv Exam3

.SH DESCRIPTION
.B gs_to_csv.sh
Converts Gradescope files to canvas files

.SH AUTHOR
Maurice Barnes